name: kiota_serialization_form
description: "Kiota serialization for form data"
version: 0.0.1-pre.1
homepage: https://github.com/ricardoboss/dart_kiota_abstractions/tree/main/packages/kiota_serialization_form
publish_to: 'none'

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  kiota_abstractions:
    path: ../kiota_abstractions

dev_dependencies:
  build_runner: ^2.4.9
  strict: ^2.0.0
  test: ^1.25.2
  mockito: ^5.4.4
  uuid: ^4.3.3
