name: microsoft_kiota_serialization_form
description: "Provides parsing and serialization support for the `application/x-www-form-urlencoded` content type."
version: 0.0.1
homepage: https://github.com/microsoft/kiota-dart/tree/main/packages/microsoft_kiota_serialization_form
repository: https://github.com/microsoft/dart_kiota

environment:
  sdk: ^3.6.0

resolution: workspace

dependencies:
  microsoft_kiota_abstractions: ^0.0.1
  uuid: ^4.5.1

dev_dependencies:
  build_runner: any
  strict: ^2.1.0
  test: ^1.25.12
  mockito: ^5.4.4
