name: microsoft_kiota_serialization_form
description: "Provides parsing and serialization support for the `application/x-www-form-urlencoded` content type."
version: 0.0.1-pre.1
homepage: https://github.com/kiota-community/dart_kiota/tree/main/packages/microsoft_kiota_serialization_form
repository: https://github.com/kiota-community/dart_kiota
publish_to: 'none'

environment:
  sdk: ^3.6.0

resolution: workspace

dependencies:
  microsoft_kiota_abstractions:
    path: ../microsoft_kiota_abstractions
  uuid: ^4.5.1

dev_dependencies:
  build_runner: any
  strict: ^2.1.0
  test: ^1.25.8
  mockito: ^5.4.4
