name: kiota_abstractions
description: "Kiota abstractions for Dart."
version: 0.0.1
homepage: https://github.com/ricardoboss/dart_kiota_abstractions
publish_to: 'none'

topics:
  - kiota
  - abstractions
  - api
  - client

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  std_uritemplate:
    git:
      url: https://github.com/std-uritemplate/std-uritemplate.git
      path: dart/

dev_dependencies:
  strict: ^2.0.0
  test: ^1.25.0
  mockito: ^5.4.4
  build_runner: ^2.4.8
