name: kiota_serialization_multipart
description: "Provides parsing and serialization support for the `multipart/form-data` content type."
version: 0.0.1-pre.1
homepage: https://github.com/kiota-community/dart_kiota/tree/main/packages/kiota_serialization_multipart
repository: https://github.com/kiota-community/dart_kiota
publish_to: 'none'

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  http: ^1.2.2
  kiota_abstractions:
    path: ../kiota_abstractions
  uuid: ^4.4.2

dev_dependencies:
  build_runner: ^2.4.9
  kiota_serialization_json:
    path: ../kiota_serialization_json/
  mockito: ^5.4.4
  strict: ^2.0.0
  test: ^1.25.2
