name: microsoft_kiota_abstractions
description: "Provides interfaces and base classes for Dart Kiota clients."
version: 0.0.1
homepage: https://github.com/microsoft/kiota-dart/tree/main/packages/microsoft_kiota_abstractions
repository: https://github.com/microsoft/kiota-dart

topics:
  - kiota
  - abstractions
  - api
  - client

environment:
  sdk: ^3.6.0

resolution: workspace

dependencies:
  meta: ^1.16.0
  std_uritemplate: ^2.0.1
  uuid: ^4.5.1

dev_dependencies:
  strict: ^2.1.0
  test: ^1.25.14
  mockito: ^5.4.5
  build_runner: any
