name: microsoft_kiota_serialization_multipart
description: "Provides parsing and serialization support for the `multipart/form-data` content type."
version: 0.0.1-pre.1
homepage: https://github.com/microsoft/kiota-dart/tree/main/packages/microsoft_kiota_serialization_multipart
repository: https://github.com/microsoft/dart_kiota

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  http: ^1.2.2
  microsoft_kiota_abstractions:
    path: ../microsoft_kiota_abstractions
  typed_data: ^1.3.2
  uuid: ^4.4.2

dev_dependencies:
  build_runner: ^2.4.9
  microsoft_kiota_serialization_json:
    path: ../microsoft_kiota_serialization_json/
  mockito: ^5.4.4
  strict: ^2.0.0
  test: ^1.25.2
