name: kiota_http
description: "Provides an implementation of a Kiota RequestAdapter that uses `http`."
version: 0.0.1-pre.1
homepage: https://github.com/kiota-community/dart_kiota/tree/main/packages/kiota_http
repository: https://github.com/kiota-community/dart_kiota
publish_to: 'none'

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  kiota_abstractions:
    path: ../kiota_abstractions
  http: ^1.2.2
  http_parser: ^4.0.2
  uuid: ^4.5.1

dev_dependencies:
  strict: ^2.1.0
  test: ^1.25.8
  mockito: ^5.4.4
  build_runner: any
