name: microsoft_kiota_serialization_json
description: "Provides parsing and serialization support for the `application/json` content type."
version: 0.0.1
homepage: https://github.com/microsoft/kiota-dart/tree/main/packages/microsoft_kiota_serialization_json
repository: https://github.com/microsoft/kiota-dart

environment:
  sdk: ^3.6.0

resolution: workspace

dependencies:
  microsoft_kiota_abstractions: ^0.0.1
  uuid: ^4.5.1

dev_dependencies:
  build_runner: any
  strict: ^2.1.0
  test: ^1.25.12
