name: tooling
description: "Tooling for the Dart Kiota packages"
version: 1.0.0
publish_to: "none"

environment:
  sdk: ^3.6.0

resolution: workspace

dependencies:
  args: ^2.5.0
  yaml: ^3.1.2

dev_dependencies:
  lints: ">=3.0.0 <6.0.0"
  test: ^1.25.14
